### ISSUE TITLE
Legacy mobile menu appears between 990px and 976px wide

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#101]
Probably an ASU-Webstandards-Bootstrap theme issue, but it looks like some part of the legacy mobile menu implementation exists in the theme as well.

![screen shot 2015-03-12 at 12 50 33 pm](https://cloud.githubusercontent.com/assets/295804/6626780/900ed1a2-c8b6-11e4-8bed-c5b57c1afda3.png)

**Comment by rraub** [comment]
FYI: I can get this to occur with OS X on chrome, firefox and safari

**Comment by idmontie** [comment]
On IE it happens at 938px to 985px.
