### ISSUE TITLE
Mobile nav items dont expand on click

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#104]
I can reproduce this on desktop and ios devices running chrome. The gios-asu.github.io pages don't have this bug so its a new issue

**Comment by idmontie** [comment]
Can reproduce, I'll look into a fix.

**Comment by idmontie** [comment]
Not an issue with the Web Standards Wordpress Theme.  It was in issue with an out of date build for the School of Sustainability Theme.

**Comment by idmontie** [comment]
I will email Chris Boone that it has been fixed in a bit, just want to make sure the file is not cached.

**Comment by rraub** [comment]
The nav works for me on the live site without clearing my cache on my phone and desktop so I think its safe to email him back.
