### ISSUE TITLE
We should note the lowest version of IE that we support

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#107]
I think right now the lowest version of IE we support is IE 9.  Whether or not we support IE 8 would be up to analytics and a vote I suppose.

**Comment by rraub** [comment]
IE 8 via litmus currently isn't pretty: 
![image](https://cloud.githubusercontent.com/assets/295804/6947581/1c7456ac-d85d-11e4-82bf-b88634c91587.png)

IE 9 and up is fine

**Comment by rraub** [comment]
Webspark fails on IE 8 too..
![image](https://cloud.githubusercontent.com/assets/295804/6947683/c180fcd6-d85d-11e4-8726-4e7730e09b52.png)

**Comment by rraub** [comment]
IE 9 and up is my vote for official support. If Microsoft stops supporting it we should to.

**Comment by idmontie** [comment]
Agreed.  I will document this and close it.
