### ISSUE TITLE
Related Links at bottom of page

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#111]
~~There should be an custom field option to turn on related links at the bottom of the page.~~

- [x] ~~Administrative panel that allows administrators to define global wide related links that will always appear first on the list of related links.~~
- [x] Related links will be shown via a shortcode at the end of your page content.
- [x] If there is a shortcode and there are less than X administrative related links and per page defined related links, peer pages should be linked to.
- [x] Styles
- [x] Documentation
- [x] Tests

**Comment by rraub** [comment]
So the shortcode is just to define where to print the links and the links themselves are stored in a custom field for each post?

**Comment by idmontie** [comment]
Strike that first line, I forgot to remove it from my post.

**Comment by idmontie** [comment]
I'm going to put the globally defined related-links on hold for now.  We don't have an administrative menu for the plugin and that feature would require one.
