### ISSUE TITLE
Customize Color Settings for Responsive Hero Title

### ISSUE THREAD

**Issue by jehollow** [gios-asu/ASU-Web-Standards-Wordpress-Theme#133]
Hi Ivan,

This is your reminder to customize the color settings for responsive hero title. See the attached image if this does not make sense.

![screen shot 2015-06-02 at 4 02 24 pm](https://cloud.githubusercontent.com/assets/9829734/7949235/cf354530-0940-11e5-83a0-b0b817eac017.png)

**Comment by idmontie** [comment]
Thanks for posting it Justin. I'll finish this up by the end of the week.
