### ISSUE TITLE
Universal Container Padding

### ISSUE THREAD

**Issue by jehollow** [gios-asu/ASU-Web-Standards-Wordpress-Theme#135]
Title says it all!
![images](https://cloud.githubusercontent.com/assets/9829734/8090064/8d61403e-0f60-11e5-8611-837c4bc42505.jpg)

**Comment by idmontie** [comment]
@jehollow Let's meet about this at some point. I'd like to roll all of the standardization of containers, headings, and paragraph tags into the base Bootstrap theme.

**Comment by idmontie** [comment]
This will be closed by the base theme.
