### ISSUE TITLE
News Sub-categories created, Need initial setup

### ISSUE THREAD

**Issue by bryanbarker** [gios-asu/ASU-Web-Standards-Wordpress-Theme#138]
The Sub-categories are created, under Sustainability Research News.  As discussed, we will place a this Sustainability Research News category on GIOS site and display all child categories together. Then, the sub-sites will have the opportunity to show Institute News as well as just their child category.

Please setup for DCDC and Lightworks. 

![screen shot 2015-06-26 at 10 04 54 am](https://cloud.githubusercontent.com/assets/9094822/8383085/63bdee7e-1bec-11e5-99e8-f0d68fac2c9a.png)

**Comment by idmontie** [comment]
Moving this issue to the appropriate repos.
