### ISSUE TITLE
iFrame un-responsive

### ISSUE THREAD

**Issue by jehollow** [gios-asu/ASU-Web-Standards-Wordpress-Theme#139]
Hey guys the shortcode for iFrames is not handling the Bootstrap responsive embed class. 
http://getbootstrap.com/components/#responsive-embed. Not sure if I am doing something wrong.

Here is a link to the page with the video
https://wp.sustainability.dev.gios.asu.edu/operations/our-commitment/principled-practice/green-labs-program/

**Comment by rraub** [comment]
The iframe short code doesn't currently support class attributes. Since thats a feature of our Wordpress Plugin I'll make a issue for this (https://github.com/gios-asu/gios2-wp/issues/126)
