### ISSUE TITLE
Request for Information Sales Force Integration

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#14]
- [ ] request semester dates
- [ ] store semester dates
- [ ] request states data
- [ ] store states data
- [ ] request countries data
- [ ] store countries data

- [ ] rfi form
- [ ] rfi request
- [ ] rfi request on before send callback
- [ ] rfi request on after send callback
- [ ] rfi request result and thank you page
- [ ] rfi form error

**Comment by idmontie** [comment]
We should ask about this on the next Friday meeting (1/16/2015).

**Comment by idmontie** [comment]
@giosweb It's been two months, we need to ask about this again.

**Comment by rraub** [comment]
In the meeting on March 27th, they said the Drupal RFI implementations would be ready for production within the first two weeks of April. Ideally if they are live with the RFI forms, they should be able give us some documentation on the middleware so we can start implementing a Wordpress version. 

Also this functionality should be in its own wordpress plugin, not all sites using the asu web standards theme are going to want the RFI forms.

In our next meeting we should ask about it.

**Comment by idmontie** [comment]
Here is the email of our last contact: Garret.Walliman@asu.edu along with Ronald Page.

**Comment by idmontie** [comment]
@rraub Right now we are using Contact Form 7 with email forwarding to get information into Salesforce. Should we close this for now and come back to it once we actually have API access?

**Comment by rraub** [comment]
@idmontie yeah, we've haven't been able to make any progress on that front in too long. The contact form 7 work around is good enough for now.
