### ISSUE TITLE
Container padding/margin off on Sustainability Site

### ISSUE THREAD

**Issue by jehollow** [gios-asu/ASU-Web-Standards-Wordpress-Theme#140]
Looks like there is more padding/margin on the left side of the container than the right.

![image2](https://cloud.githubusercontent.com/assets/9829734/8531308/3d361c08-23db-11e5-900d-3bc10bf9d494.PNG)
![image1](https://cloud.githubusercontent.com/assets/9829734/8531309/3f33c938-23db-11e5-8fdd-8446a00ec5c9.PNG)

**Comment by idmontie** [comment]
I will need access to an iPad to test this since I cannot replicate it on my desktop.

**Comment by idmontie** [comment]
Can no longer duplicate. Closing.
