### ISSUE TITLE
Add support for WordPress 4.3 Site Icons

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#163]
In 4.3 they added [Site Icons](https://make.wordpress.org/core/2015/07/27/site-icon/), we should see if we can integrate the ASU icons into this.

**Comment by rraub** [comment]
I just tested it and if a user defines a site icon it will be included in addition to the icons this theme defines. I'm not sure how valid that is, but my browser doesn't complain.

**Comment by idmontie** [comment]
Do we even want this if all of our sites should use the same favicon?

**Comment by rraub** [comment]
We should probably disable it or start using it with a default value. Right now it shows up as an option: 
![screen shot 2015-10-23 at 8 36 36 am](https://cloud.githubusercontent.com/assets/295804/10697559/613316a2-7961-11e5-8d79-8e1b9fe46e1b.png)

and if someone fills it out they would have two site icons defined.
