### ISSUE TITLE
Add a fine tuning adjustment to the menu item padding to prevent line wrapping

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#165]
In the customizer we should allow themes to adjust the padding for menu items so they can fine tune the width of the menu.

**Comment by idmontie** [comment]
:+1:

**Comment by rraub** [comment]
Would you be able to adjust the padding for a particular window width? 
e.g. dcdc's nav only breaks on the LG size, MD and XL are fine.

**Comment by idmontie** [comment]
Probably not, that would make it really complicated and people would just ask us how it works over and over again. I'll need to see if a simple set margin for all the buttons would suffice.

**Comment by idmontie** [comment]
Must fix for DCDC Site
