### ISSUE TITLE
Implement Updates

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#178]
Find a way to hook into WordPress's update feature. Either that or use Github Updater

**Comment by rraub** [comment]
if we separate out the shortcodes into an accompanying plugin we could go the route of publishing the theme to WordPress.org.  

Did your other theme ever get approved @idmontie?

**Comment by rraub** [comment]
FYI: I just tried out the github-updater v5.2.0 and it throws a bunch of warnings, but it seems to work. It was able to update our theme successfully on my local site.

**Comment by idmontie** [comment]
@rraub Does that also mean we can stop maintaining a fork of the github updater?

**Comment by rraub** [comment]
I think so, however we should try it on dev first.

**Comment by idmontie** [comment]
I am going to start testing this on dev.

**Comment by rraub** [comment]
:cat: cool

**Comment by idmontie** [comment]
It works!
