### ISSUE TITLE
Remove the street address from the footer

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#180]
Webspark has already done this. Additional benefit will be shortening the height of the footer. The address should be on a contact or about page.

**Comment by idmontie** [comment]
The Campus Address and Additional Address are already optional.

**Comment by rraub** [comment]
Optional Yes, but should it even be an option if its not part of the standards?

**Comment by rraub** [comment]
Ping: this was brought up today, we should add this into the next release.

**Comment by rraub** [comment]
We should remove the `Campus Address` field all together and Rename the `School Address` field to something more general like `Text below logo in Footer`.

Also the Phone and Fax options should be labeled as optional since they are.

<img width="292" alt="screen shot 2017-02-16 at 1 42 23 pm" src="https://cloud.githubusercontent.com/assets/295804/23040218/c591358a-f44d-11e6-9e04-f2cc6c6b7e90.png">

**Comment by anuranduttaroy** [comment]
Done.

**Comment by rraub** [comment]
@anuranduttaroy could you make a Pull Request for it?
