### ISSUE TITLE
Main menu: Home icon is taller than other menu items

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#201]
The home icon is 58px high and the rest of the top level menu is 57px high. Its minor, but noticeable.
![screen shot 2015-12-21 at 1 38 37 pm](https://cloud.githubusercontent.com/assets/295804/11940964/5af2faf8-a7e9-11e5-8210-96ea07c24c8b.png)

**Comment by rraub** [comment]
@idmontie did you see this?

**Comment by idmontie** [comment]
I haven't seen it yet, thanks for the ping.

**Comment by rraub** [comment]
@idmontie thoughts?

**Comment by idmontie** [comment]
I think this is fixed now...

**Comment by idmontie** [comment]
Fixed, except for the hover effect: 
![image](https://cloud.githubusercontent.com/assets/412382/13413017/8784ac4a-df04-11e5-8008-d22ffcec0dd6.png)

**Comment by idmontie** [comment]
Needs:

```css
.nav li:first a {
  height: 57px;
}
```

**Comment by idmontie** [comment]
Closing in the next version of the Web Standards Bootstrap Theme.
