### ISSUE TITLE
Sidebar widgets

### ISSUE THREAD

**Issue by stephmabee** [gios-asu/ASU-Web-Standards-Wordpress-Theme#211]
Is it a possibility to get sidebar widgets available in the theme? We use widgets frequently to provide RSS content or small bits of important information.

We've got a couple of workarounds going, but some information that we'd like to appear on many pages will quickly become a pain to maintain if it's handcoded onto several pages instead of one widget.

**Comment by rraub** [comment]
We haven't really used any common sidebars, only a few pages of ours have a sidebar at all.  Right now the widget area in the only sidebar for this theme shows up on the right of a post (not a page).

We could look at adding a new page template with a sidebar or have a widget area show up via a short code. Which way would you view more useful?

**Comment by bergeson** [comment]
@rraub, I was talking with Stephanie about this today and I think the short code option would be best for our needs.
