### ISSUE TITLE
Post Featured image functionality?

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#212]
Is it possible to have Featured image capability for posts? I thought this was a WordPress feature for any theme, but I cannot see the Featured image capability in any of the posts I create. I checked to see if it was a screen option, but it is not. And a quick Google search doesn't leave lead me to a solution, so I'm checking with you. Thanks!

**Comment by idmontie** [comment]
Hey there @bergeson !

You are right that the "Set Featured Image" feature is missing from the theme. We We opted for a different approach to setting page features because we also needed to support custom titles and descriptions for the hero image.

First, make sure you have "Custom Fields" enabled for your post:
![image](https://cloud.githubusercontent.com/assets/412382/12425849/f1fa91c0-be93-11e5-9d45-0678f125839e.png)

Then, after writing your post content, you can set the following custom fields:
![image](https://cloud.githubusercontent.com/assets/412382/12425821/ddd1bbc4-be93-11e5-9e41-f8ef6ff5809e.png)

Which, in this example will add a hero image to your page like this:
![image](https://cloud.githubusercontent.com/assets/412382/12425882/21f7d55e-be94-11e5-84a8-7207d78b1339.png)

**Comment by bergeson** [comment]
Ok, this is by far the quickest, most thorough customer service I've ever received. :) Thank you @idmontie!

**Comment by idmontie** [comment]
Thanks! Feel free to open another issue if you have any other questions. We will also mark this as something that we need to document.

**Comment by bergeson** [comment]
Will this only work for a hero image? I was wanting just to add a small image, actually. I'm replicating this page http://ssebe.engineering.asu.edu/research/centersandclusters.html and wanting to just have the small images be associated with the short descriptions in a post.

**Comment by idmontie** [comment]
I don't think we have anything like that. We can discuss adding in this week's WordPress meeting.

**Comment by bergeson** [comment]
Thank you! It is really great having this theme. Thanks so much for creating it!

**Comment by bergeson** [comment]
I know this topic is closed, but want to know how hard it is to bring back the featured image functionality in this theme? I'm realizing how much I depend on it in its absence. Since it is part of WordPress, can it be "switched on" easily? Or will it interfere with the hero image setup you've created? Thanks!

**Comment by rraub** [comment]
The page featured image would be a nice addition, however it isn't as easy to add. There are a few issues:
* **Social image thumbnails** - currently these automatically get set from the page featured image if there is one, and I doubt a full width hero image would work well for that. 
* **Featured image sizes** - By default WordPress expects the thumb, medium, and large size versions of images to be square which is totally not intended for the wide hero image. We would have to play around with defining a new image sizing scheme that could accommodate these.
* Which image do we use if there is a custom field defining a page_feature_image and a featured image? - we will just have to decide which one wins, probably the custom field since thats less restrictive and gives more options to choose from (like color).

What do you think about using the title and description of the featured image to populate the text on the hero image? 
![screen shot 2016-02-02 at 3 40 40 pm](https://cloud.githubusercontent.com/assets/295804/12766910/5b7b1798-c9c3-11e5-9e1d-61dc892ba136.png)

**Comment by rraub** [comment]
After looking into this further, the title and description for a featured image is on that image. So if we used that for the hero text that would be the same for every page that used that hero image (unless its overridden by the page_feature_title or page_feature_description).

The sizing is something that can be worked out, but what is harder is the post thumbnail. I don't think its desirable for the hero image to be the thumbnail for a post. WordPress will automatically pull out the first image from the posts body to use as the post thumbnail if there is no featured image, which is what we want. I imagine you use post thumbnails for your sites right?

The better solution in the long run could be to add a custom image picker for posts just for hero images.

**Comment by bergeson** [comment]
Thanks, @rraub for looking into this so thoroughly. Yes, it is the post thumbnails that I need the most, and yes, a hero image is not right for a square thumbnail. On this page (http://move.engineering.asu.edu/research-centers-clusters-labs/) I used the Divi Builder plugin to layout posts in a grid format. If the posts had a featured image, it would appear within the post. Now, I've learned that the Divi Builder plugin does not play well with a few other features of this theme, so I'm moving away from it. This page (http://move.engineering.asu.edu/category/news/) is showing a set of posts with image, but that is just the actual post on display, not the thumbnail being pulled out. I'd love to lay them out in a more compact way with a thumbnail, too.

In addition to using your theme, we are going to look into making a Divi child theme that will meet the ASU standards, so I don't want you to go out of your way to find a solution for this (for us, specifically). So many of our sites are built in Divi, and the few people who actually work on their own sites are quite accustomed to it. I do think the featured image is a useful feature (sorry! ha ha) and the "automatic" thumbnails in certain layouts are really nice, so maybe others who use this theme will want it. Thank you so much!

**Comment by rraub** [comment]
@bergeson if you would like we can setup a meeting to look at some of the areas that divi builder is not playing nice with this theme. Just to make sure it isn't something easy to fix. 

Its possible to enable the featured images for posts and just not display them, that would get the post thumbnails working for you. However the risk is then it becomes confusing to everyone else why there is a featured image selection that seems to do nothing.

**Comment by bergeson** [comment]
Hi Ryan,
I've debated over whether to bother you about this or not and I think I do
want to bother you. :) Can we set up a meeting? I'm generally available
between 9-3 CST, M-Th, with a break midday for lunch. I'll work around your
schedule as I'm flexible.

The biggest thing I'm hoping for is to have the ability to show images in
my posts, and to have link and font styles carry through into the Divi
Builder.

So, I have got one page where the image I put in a standard post will show
up in the blog: http://move.engineering.asu.edu/category/news/

It is a category page showing News posts (in progress - please ignore the
repeat of the information in the sidebar! :) ). I did not  use the Divi
Builder to build the posts or the layout of the blog. The font and link
styles show up too.

Here is a blog showing the same news that was built in Divi Builder. It
will show a featured image if I can set one, but not the first image from
the post.

The Directory is one I really want to get sorted out:
http://move.engineering.asu.edu/directory/
The Posts are actually "Projects" and the layout is made using a Builder
element called a Filterable Portfolio. Featured images would be displaying
the faculty photos if I could set them.

Ok, that's enough to chew on for now. Let me know when you can meet.
Thanks so much, Ryan!
Kristin

On Thu, Feb 4, 2016 at 3:29 PM, Ryan Raub <notifications@github.com> wrote:

> @bergeson <https://github.com/bergeson> if you would like we can setup a
> meeting to look at some of the areas that divi builder is not playing nice
> with this theme. Just to make sure it isn't something easy to fix.
>
> Its possible to enable the featured images for posts and just not display
> them, that would get the post thumbnails working for you. However the risk
> is then it becomes confusing to everyone else why there is a featured image
> selection that seems to do nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/212#issuecomment-180060681>
> .
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu

**Comment by bergeson** [comment]
Forgot to put in the link to the Divi Builder Blog example:
http://move.engineering.asu.edu/news-2/

Also, I wanted to send an example of a Divi directory that displays the
images so you had an idea what I'm shooting for:
http://ecee.engineering.asu.edu/directory/.

Thank you!

On Wed, Feb 17, 2016 at 7:07 AM, Kristin Gasser <bergeson@asu.edu> wrote:

> Hi Ryan,
> I've debated over whether to bother you about this or not and I think I do
> want to bother you. :) Can we set up a meeting? I'm generally available
> between 9-3 CST, M-Th, with a break midday for lunch. I'll work around your
> schedule as I'm flexible.
>
> The biggest thing I'm hoping for is to have the ability to show images in
> my posts, and to have link and font styles carry through into the Divi
> Builder.
>
> So, I have got one page where the image I put in a standard post will show
> up in the blog: http://move.engineering.asu.edu/category/news/
>
> It is a category page showing News posts (in progress - please ignore the
> repeat of the information in the sidebar! :) ). I did not  use the Divi
> Builder to build the posts or the layout of the blog. The font and link
> styles show up too.
>
> Here is a blog showing the same news that was built in Divi Builder. It
> will show a featured image if I can set one, but not the first image from
> the post.
>
> The Directory is one I really want to get sorted out:
> http://move.engineering.asu.edu/directory/
> The Posts are actually "Projects" and the layout is made using a Builder
> element called a Filterable Portfolio. Featured images would be displaying
> the faculty photos if I could set them.
>
> Ok, that's enough to chew on for now. Let me know when you can meet.
> Thanks so much, Ryan!
> Kristin
>
> On Thu, Feb 4, 2016 at 3:29 PM, Ryan Raub <notifications@github.com>
> wrote:
>
>> @bergeson <https://github.com/bergeson> if you would like we can setup a
>> meeting to look at some of the areas that divi builder is not playing nice
>> with this theme. Just to make sure it isn't something easy to fix.
>>
>> Its possible to enable the featured images for posts and just not display
>> them, that would get the post thumbnails working for you. However the risk
>> is then it becomes confusing to everyone else why there is a featured image
>> selection that seems to do nothing.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/212#issuecomment-180060681>
>> .
>>
>
>
>
> --
> Kristin B. Gasser
> Web Application Developer
> Engineering Communications
> kbgasser@asu.edu
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu

**Comment by bergeson** [comment]
Hi @rraub, you had said "Its possible to enable the featured images for posts and just not display them, that would get the post thumbnails working for you." Could this be an option for the short term?

**Comment by rraub** [comment]
Sorry for the delay! This could be an option, however I was hoping to find a better solution for the long term. I dont have a divi site to test this on, but you could try it by un-commenting this line: https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/master/functions.php#L44
in the theme on one of your sites to enable the featured images to see if that works. 

I would rather not release a new version of this theme just to test if these featured images work for Divi. Can you give it a try on your end? if it does work we can officially include it in the next release.

**Comment by bergeson** [comment]
No worries about the delay! Thank you so much for looking into this. I made
the change but it did not have an effect, as the option to add a featured
image is not available in the post, so I've not assigned any featured
images to any posts. It is usually the last option in the right column of a
post page.

On Mon, Feb 29, 2016 at 1:09 PM, Ryan Raub <notifications@github.com> wrote:

> Sorry for the delay! This could be an option, however I was hoping to find
> a better solution for the long term. I dont have a divi site to test this
> on, but you could try it by un-commenting this line:
> https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/master/functions.php#L44
> in the theme on one of your sites to enable the featured images to see if
> that works.
>
> I would rather not release a new version of this theme just to test if
> these featured images work for Divi. Can you give it a try on your end? if
> it does work we can officially include it in the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/212#issuecomment-190338254>
> .
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu

**Comment by rraub** [comment]
Did you try disabling and re-enabling the theme?

**Comment by bergeson** [comment]
That worked! And I'm getting thumbnails where I need them in the Divi
builder components. I'm not getting them on regular posts, which is what I
expected. That will do wonderfully for now! Thank you.

On Mon, Feb 29, 2016 at 1:24 PM, Ryan Raub <notifications@github.com> wrote:

> Did you try disabling and re-enabling the theme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/212#issuecomment-190344872>
> .
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu

**Comment by rraub** [comment]
That settings should enable featured images for both posts and pages, it does for me anyway. I will add these native featured images into the next release of this theme.
