### ISSUE TITLE
Edit button doesn't work

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#214]
When I click on an "Edit" button in a post or page, nothing happens. ?

**Comment by bergeson** [comment]
Sorry, to clarify, I mean the Edit button built into the theme.

**Comment by idmontie** [comment]
Bug confirmed. It should be an easy fix that we will add to the next release.

**Comment by bergeson** [comment]
Thank you!
