### ISSUE TITLE
Projects vs. Posts - Projects lacking category in "This entry posted in ____" text at bottom

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#216]
Hi,
I use WP Projects to create faculty directories. I notice at the bottom of each Project the "This entry posted in" sentence is not being auto-populated with the category, as it is with regular posts: http://move.engineering.asu.edu/project/xuesong-zhou/

I would actually like to be able to remove the "This entry was posted in ______ . Bookmark the permalink." from the bottom of all the directory (Project) pages. Is it possible to turn that off? Or does it involve editing it out of the Projects page code?
Thanks!

**Comment by bergeson** [comment]
In fact, I'd like to not show the publication date, too.

**Comment by idmontie** [comment]
It looks like the HTML generated by WordPress is similar to that of a post except the project plugin adds `.single-project` to the post.

We can tackle this one of two ways:

1. CSS to just hide those navigation items
2. Stop the HTML from being generated at all unless we are rendering a normal post.

We also have to add to the road map that we need to standardize how posts are rendered. I don't think anyone at ASU wants "Posted on [Date] by [Author]" and "This entry was posted in [Category]. Bookmark the permalink. Post navigation [Next Post Link] →" on their posts.

**Comment by idmontie** [comment]
Also, @rraub: Thoughts on the WP Projects plugin? @bergeson do you have a link to the plugin's homepage?

**Comment by rraub** [comment]
I agree that i doubt anyone wants "Posted on [date] by [author]", so we should probably remove them or to address this specific issue check for the instance when there is no categories to show and just omit that line. 

The Permalink is feature that I think is hardly used and can be removed.

For a quick solution you could just hide the footer for projects via css:
```css
article.project footer { 
  display: none;
}
```

**Comment by bergeson** [comment]
Thanks for the CSS - I'll use it. Do I add it to one of the CSS files? If so, which one? I would like to avoid doing anything that will be over-written in an update, but I also don't want to make a child theme (if that is even possible). Just let me know what's best.

I agree that it would be better to remove the auto-generated text at the bottom. I'm not even sure I want it on regular posts, to be honest. I like controlling that kind of stuff from post to post or category to category. Thanks so much!

**Comment by rraub** [comment]
since your just adding css you shouldn't need to use a child theme, for some of our sites that have minor CSS changes like this we've been using this plugin https://wordpress.org/plugins/simple-custom-css/ 

Now if you find yourself needing to do the same things on multiple sites then that might be more of a case for a child theme.

**Comment by bergeson** [comment]
Thanks for the plugin lead, @rraub!
