### ISSUE TITLE
Bullets stripped from lists in Projects and Posts

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#217]
Good morning! When I put a <ul> in a project, the bullets are stripped out of the list items:
http://move.engineering.asu.edu/project/shane-underwood/

Is the list style defined by the theme? Or is this some WP oddity?

**Comment by idmontie** [comment]
Looks like a Divi Builder oddity?

From inspecting the element, I can see that there are two styles that are setting the `list-style` to `none`:
![image](https://cloud.githubusercontent.com/assets/412382/12486037/0c77429c-c01e-11e5-9ec8-4eceb5455725.png)

I'm not sure that the best solution for this would be. Is there a way to change this behavior in Divi?

**Comment by bergeson** [comment]
Thank you! Should have taken that step myself! I'll look into it. I'm trying out the Divi builder on some pages with this theme, because we have lots of sites built in Divi, and the non-coders who edit their own pages are very familiar with it, and are not really able to edit straight html effectively, so we want to introduce some consistency when people go to edit their sites. Thanks!
