### ISSUE TITLE
add a recommended or required plugin - github updater

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#223]
Apparently this is a WordPress 4 feature, but there are also third party ways to get this functionality.

**Comment by rraub** [comment]
@idmontie can you find how to do this using WordPress Core? All I can find is methods using https://github.com/TGMPA/TGM-Plugin-Activation

**Comment by idmontie** [comment]
I was just investigating this.

**Comment by idmontie** [comment]
Hmm it looks like that might be it. Not in the core like I thought it was :(

**Comment by rraub** [comment]
With it not being in core, do you think their solution is worth implementing?

**Comment by idmontie** [comment]
Maybe later? I think it would be useful to recommend Yoast, the HTML Editor, etc. But it still won't install Github Update for us since that is not on the WordPress plugin "store".

**Comment by rraub** [comment]
The github updater is the main one I would like push for as a required dependency. However we do use a few features from Yoast that would be a good recommendation. I agree we should probably wait until these features get better support.
