### ISSUE TITLE
Internal documentation?

### ISSUE THREAD

**Issue by stephmabee** [gios-asu/ASU-Web-Standards-Wordpress-Theme#225]
I remember finding some internal documentation on the theme that had information about the ratio header and slim header. But I can't find it again :( and I think the slim header may be useful for a set of pages I'm working on. Can you point me in the right direction?

**Comment by idmontie** [comment]
I actually don't think we have the exact sizes documented anywhere. @rraub Can you find any docs?

Here is a link about the HTML for [section heros](https://gios-asu.github.io/ASU-Web-Standards-Bootstrap/section-heros.html).

And here is [documentation on the custom fields](https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme#new-page-fields).

**Comment by stephmabee** [comment]
Section heros is the page I found before! Is there a preferred method or suggestion for changing the background color of the text only hero? I think "dark" will be fine, but just in case. Or should I use inline styles? 

I may also be remembering something about using color as backgrounds for the slim hero from a WP users group meeting (a loooong time ago).

**Comment by rraub** [comment]
The hub says its height should be between 380px - 700px, and 1170px wide. We have been using 1400x435 size on our sites. 

As far as the styles go, a number of our hero texts have inline styles to help contrast with the background image. 

We do have a `page_feature_color` that can take `black`, `white`, `gold`, or `maroon` values ([read more](https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/2f410c7ab5ebcc63fc9574d638336032f0208012/inc/shortcodes/page-features-shortcode.php#L16-L21)).

Does that work?

**Comment by stephmabee** [comment]
Thanks, Ryan! I think was looking more for the different hero options. We have a handful of pages where we do not have a good photo options (photos were submitted or are portraits of people), but I still want a hero and h1 on the page.

I have played around with the feature color that changes the color of the text, but I was thinking more along the lines of could I have a text only hero with a maroon background (for example).
