### ISSUE TITLE
There are two h1's per page

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#241]
The site title and the page feature title are both h1s, which is not allowed.

We need to pick one to be the h1 and have the other one be an h2 with the class `h1` (or similar).

This may also involve a change to the underlying CSS to get the font sizing correct.

**Comment by rraub** [comment]
The site title shouldn't be an h1, we could use a h1 span class instead. Or adjust styling on .site-title as you proposed.

**Comment by idmontie** [comment]
Other webspark sites and [this answer from stackoverflow](http://stackoverflow.com/questions/268475/h1-in-article-page-site-title-or-article-title) suggest that the site title be the h1 and then the page title be the h2.

Which would mean restructuring most of our pages.

**Comment by idmontie** [comment]
Surprise! https://github.com/ASU/webspark-drops-drupal7/pull/109/files They are changing h1 to div in Webspark for the site title.

**Comment by rraub** [comment]
solved in https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/pull/257
