### ISSUE TITLE
Pingback link is rendered

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#242]
We are getting a report that we have a bad value for the pinkback link. Not sure why since it should not be rendered in the first place:

https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/7ba9e4c508fd1bf114a2ea91ccfe0401d28539e0/header.php#L141-L143

The error reported:

> Bad value for the href on element link: Must be non-empty

```
  <link rel="profile" href="http://gmpg.org/xfn/11">
      <link rel="pingback" href="">
  
```
It is showing up on the [School of Sustainabiltiy site](https://schoolofsustainability.asu.edu/). Simply view the source to see it.

**Comment by chasethenag420** [comment]
While reading about pingback I came across xmlrpc attack which is kind of brute force attack, DOS, DDOS and spam. And I see many articles suggesting to remove them(profile and pingback) if we do not need comments tracking. As we are disabling comments do you think it is good idea to remove these links itself?

**Comment by rraub** [comment]
regardless of us wanting it or not, we shouldn't render an empty href attribute. I don't think we will want to use it.
