### ISSUE TITLE
Footer menu with one level is missing ul tag

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#245]
When a footer menu only has one level the parent ul tag is not present, leaving li's on their own and not getting the right css styles applied.

**Comment by chasethenag420** [comment]
items_wrap default behaviour is to wrap in ul tag but as we are using custom format %3$s it is shown as bullet point list. 

https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/master/footer.php#L324
