### ISSUE TITLE
Alternative for navigation menus that are too wide

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#248]
@idmontie what do you think about using something like this https://github.com/VPenkov/okayNav for this theme?

**Comment by idmontie** [comment]
What would happen to menu items with dropdowns?

**Comment by rraub** [comment]
Looks like we might have to implement that on our own: https://github.com/VPenkov/okayNav/issues/4 

Still I like the idea of folding up items that don't fit rather than line wrapping.
