### ISSUE TITLE
New post creates a blank page

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#260]
Hi, I recently setup a new site using the theme, and when I create any type of Post (Post or Project), I can create it, edit and publish it, but when viewed it shows a completely blank page (no header, footer, nothing -- just white).

We are running the latest version; I tested for plugin conflicts (none), I checked the database (analyze, repair -- no issues before or after), and finally I tried switching to the default theme. In TwentySixteen I could create and successfully publish a post with a featured image.

The one thing that happens in **both** themes is that when I go to add a featured image from the media library, I can select one, then in the edit screen it appears as a broken link:
![screen shot 2016-04-11 at 9 23 15 am](https://cloud.githubusercontent.com/assets/16543935/14430406/1b696544-ffc7-11e5-99b8-90d5df1a4301.png)

However, the featured image does appear correctly in the published post (in the TwentySixteen theme). Could that be a filepath issue between the media library and where posts are being published?

Anyway, I'd love your help! :) Thanks!

**Comment by rraub** [comment]
You should check your server error logs to see if there are some errors in there. A white page with nothing to me says php error of some sort.

**Comment by rraub** [comment]
@bergeson did you get this figured out?

**Comment by bergeson** [comment]
Had FTP issues this week but finally got in this morning. Error log says:

[15-Apr-2016 12:18:05 UTC] PHP Fatal error:  Can't use function return
value in write context in
/home/engtech/public_html/wp-content/themes/ASU-Web-Standards-Wordpress-Theme/single.php
on line 30

Line 29-30 pertain to the sidebar

     $sidebar_class = 'col-sm-4 hidden-xs';
    if ( empty( trim( $sidebar_content ) ) ) {
     // if the sidebar has no content then the page should take it all up



On Fri, Apr 15, 2016 at 8:57 AM, Ryan Raub <notifications@github.com> wrote:

> @bergeson <https://github.com/bergeson> did you get this figured out?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/260#issuecomment-210473141>
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu

**Comment by rraub** [comment]
gotta love php.. looks like you are running a version of php 5.4. This is why I didn't see the error before.

**Comment by bergeson** [comment]
:-/ Thanks, Ryan!
