### ISSUE TITLE
Child theme friendly?

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#261]
I tried to create a child theme to address just a few CSS issues that show up in Divi Builder modules (link formatting, bullet lists, etc.). Although I have the parent theme name correct, when I add the child theme, I get an error that "The parent theme is missing. Please install the "ASU Web Standards Wordpress Theme" parent theme."

Is the theme able to have a child theme? Thanks!

**Comment by rraub** [comment]
Yes in fact we have a few child themes currently. 
One oddity is that the template name in the style.css header is the folder name of the parent style, not the parent theme name.
```
Template:     ASU-Web-Standards-Wordpress-Theme
```

**Comment by bergeson** [comment]
Thanks, Ryan!

On Wed, Apr 13, 2016 at 12:14 PM, Ryan Raub <notifications@github.com>
wrote:

> Yes in fact we have a few child themes currently.
> One oddity is that the template name in the style.css header is the folder
> name of the parent style, not the parent theme name.
>
> Template:     ASU-Web-Standards-Wordpress-Theme
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/issues/261#issuecomment-209550323>
>



-- 
Kristin B. Gasser
Web Application Developer
Engineering Communications
kbgasser@asu.edu
