### ISSUE TITLE
Hero image functionality disappeared from page editor after theme update

### ISSUE THREAD

**Issue by Haythamamin** [gios-asu/ASU-Web-Standards-Wordpress-Theme#289]
Before the last update a user could add Hero image though the page editor, now this function disappeared.

**Comment by rraub** [comment]
The last update shouldn't have effected hero images on pages, the hero images should still be configured using the custom fields for pages. We did enable a featured image selection for posts, but that is not used as a hero image. I've seen the custom field menu get removed from a users edit window which results in these fields disappearing. Could that be what your experiencing? 

https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme#hero-images

**Comment by Haythamamin** [comment]
Thanks, Ryan this solved it. Please mark this issue as Closed.
