### ISSUE TITLE
Font size should scale down at mobile widths

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#30]
Mainly for heading tags, in mobile view its still the same font size as the desktop widths.

**Comment by idmontie** [comment]
Also applies to nav bar and the entire site in general.  Fonts are just way too big on mobile.

**Comment by idmontie** [comment]
Something like:
```
@media(max-width: 1200px) {
  .navbar-collapse ul li a.dropdown-toggle {
    padding-left: 10px;
    padding-right: 10px;
    font-size: 0.9em;
    padding-top: 21px;
  }
}
```

**Comment by idmontie** [comment]
This will be fixed in https://github.com/gios-asu/ASU-Web-Standards-Bootstrap
