### ISSUE TITLE
Child theme CSS won't connect 

### ISSUE THREAD

**Issue by lilyalta** [gios-asu/ASU-Web-Standards-Wordpress-Theme#315]
Hi, 
I'm a bit new to this process, but created a webspark child theme and can't seem to get the child theme CSS to work. I appreciate your help! 
Lily Altavena

**Comment by nathan-rollins** [comment]
Are you asking about creating a Webspark child theme for Drupal? This project is the ASU WebStandards theme for Wordpress. If indeed you are working on a theme for Drupal, you can get free technical support from the UTO Drupal support office (https://brandguide.asu.edu/web-standards/webspark). From that page:

>Need help? Call or drop by the UTO Drupal support office. Assistance is available only for ASU
>affiliates working with Drupal Webspark sites and questions regarding the new ASU web
>standards. The service is first-come, first-served.
>
>Can't make it into USB? Ask for a video conference!

**Comment by lilyalta** [comment]
Hi Nathan, 
We're using this ASU WebStandards Wordpress theme.

**Comment by lilyalta** [comment]
Hi Nathan,

We're not using Drupal, we're using the ASU WebStandards theme for
Wordpress.

**Comment by nathan-rollins** [comment]
Ok. Let's move this to email then.

**Comment by lilyalta** [comment]
Sounds good. Would you be free for an in-person visit, by any chance? I'm a
graduate assistant at the Cronkite School building a website for a
non-profit disability and journalism organization that's out of ASU.

**Comment by lilyalta** [comment]
Lily Altavena has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=366668462857-3qkidqn8oseh9v3fhm3085kpb747bgm7.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.download%2Fg.php&customparam=customparam>
