### ISSUE TITLE
Old logo in Print styles

### ISSUE THREAD

**Issue by bryanbarker** [gios-asu/ASU-Web-Standards-Wordpress-Theme#345]
When you print from any page, the old ASU logo is used and needs to be updated.

**Comment by nathan-rollins** [comment]
Test comment to see if the Teamwork integration syncs issue contents like comments.

**Comment by bryanbarker** [comment]
I received a Cc, and am responding to everyone!

Yay!


Best regards,
Bryan

Web & Design Program Manager
Global Institute of Sustainability

Sustainability.asu.edu<https://sustainability.asu.edu/>
SchoolofSustainability.asu.edu<https://schoolofsustainability.asu.edu/>

**Comment by nathan-rollins** [comment]
This has been resolved. Closing.
