### ISSUE TITLE
add [row] shortcode

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#69]
We have [container] and [column] but no row shortcode? It should probably take the same attributes as the container shortcode.

**Comment by idmontie** [comment]
Should we implement the `[row]` shortcode, or just use [this plugin](https://wordpress.org/plugins/bootstrap-3-shortcodes/) that you found?

**Comment by rraub** [comment]
I think we should try and use that plugin if we can, a row shortcode is just one of the many things we would want to add if we wanted to support more of the bootstrap components.

**Comment by idmontie** [comment]
Would our container and column shortcodes conflict with the bootstrap plugin?

**Comment by idmontie** [comment]
Might as well do this one too: https://wordpress.org/plugins/font-awesome-shortcodes/

**Comment by idmontie** [comment]
The plugin also says:

> This plugin does not include the Bootstrap framework

So, sounds like a good plugin to me.  It's even on Github. https://github.com/filipstefansson/bootstrap-3-shortcodes

**Comment by idmontie** [comment]
No longer relevant now that we will be using the in page editor.
