### ISSUE TITLE
Coding Standards completely destroyed

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#73]
@rraub We've got a huge issue with the coding standards.

Commit ba83b727c868ee4c7b508b2a5ad33dc0c656000d completely destroyed the indentation that we had on most of our files that had HTML in them.  This commit was because you ran the automated fixer.

My code will no longer pass Grunt, I'm not sure how it ever passed Grunt on your end.

**Comment by rraub** [comment]
I'm not having an issue with the coding standards and neither is travis.. probably an issue on @idmontie 's end.
