### ISSUE TITLE
People lists have an extra row

### ISSUE THREAD

**Issue by bryanbarker** [gios-asu/ASU-Web-Standards-Wordpress-Theme#77]
Seems like there is an extra row, that's not needed here:  <div class="person-blurb row space-bot-sm">  It's throwing all people lists too wide

**Comment by rraub** [comment]
fixed in the gios2-api: https://github.com/gios-asu/gios2-php/commit/14fd48bdd980a15b0660059cb3bbeee4a16dcd74
