### ISSUE TITLE
upgrade to ASU header v5.0

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#79]
we are currently at v4.0
https://drupal.asu.edu/build/asu-header-footer-version-43

**Comment by rraub** [comment]
On Hold until v5.0, we've pulled in the big visual change to the menu items. 

Related: https://asudev.jira.com/projects/WSHF/issues/WSHF-7?filter=allopenissues and https://asudev.jira.com/projects/WSHF/issues/WSHF-8?filter=allopenissues

**Comment by idmontie** [comment]
Still on hold. The header is on hold by UTO.

**Comment by idmontie** [comment]
Duplicate of #222 . 4.4 will come out before v5 and will "most likely" fix the problems we were having with the header (which was the responsiveness).
