### ISSUE TITLE
Possible optional meta tags?

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#93]
Family friendly and audience meta tags.  Apparently part of open graph?  Need to look into it.

```
<meta
  itemprop="isFamilyFriendly"
    content="true"
>
<meta
  itemprop="audience"
    content="web designers"
>
```

**Comment by idmontie** [comment]
For the `isFamilyFriendly` tag, there is a similar meta tag:`<meta name="rating" content="General" />`

**Comment by rraub** [comment]
I'm all for the ```isFamilyFriendly``` tag, sounds like the simple one to just turn on site wide. 

However ```audience``` starts to get tricky, we probably would want it per page and what are the types of audiences to pick from? This really reminds me of some of the things we could define with https://schema.org. And thats a much bigger can of worms.

**Comment by idmontie** [comment]
Not in the standards, and not very helpful to the theme. I'm just going to close this.
